[package]
name = "symm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.2"
approx = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
